"""Initial baseline migration

Revision ID: 4f55c5396e99
Revises: 
Create Date: 2026-05-11 16:00:42.672641
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4f55c5396e99'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sites', sa.JSON(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('items_succeeded', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_states',
    sa.Column('site', sa.String(length=20), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('state_file_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('site')
    )
    op.create_table('scrape_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scrape_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_items_sku'), 'scrape_items', ['sku'], unique=False)
    op.create_table('part_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('sku_searched', sa.String(length=100), nullable=False),
    sa.Column('sku_found', sa.String(length=100), nullable=False),
    sa.Column('exact_match', sa.Boolean(), nullable=True),
    sa.Column('site', sa.String(length=20), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('raw_title', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['scrape_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_results_sku_searched'), 'part_results', ['sku_searched'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_results_sku_searched'), table_name='part_results')
    op.drop_table('part_results')
    op.drop_index(op.f('ix_scrape_items_sku'), table_name='scrape_items')
    op.drop_table('scrape_items')
    op.drop_table('session_states')
    op.drop_table('scrape_jobs')
    # ### end Alembic commands ###
